version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotsix-app
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_DEV_PASSWORD}
      TZ: Asia/Seoul
    restart: on-failure  # 운영용: restart: always
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7.2
    container_name: hotsix-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "${REDIS_DEV_PASSWORD}"]
    restart: on-failure  # 운영용: restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_DEV_PASSWORD}", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis-data: