spring:
  datasource:
    url: jdbc:mysql://hotsix-db.cbwe20uqwfqp.ap-northeast-2.rds.amazonaws.com:3306/hotsix_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 60000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${PROD_OAUTH2_SOCIAL_LOGIN_URI}/login/oauth2/code/kakao

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: ${PROD_OAUTH2_SOCIAL_LOGIN_URI}/login/oauth2/code/google

          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            scope: name, nickname, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${PROD_OAUTH2_SOCIAL_LOGIN_URI}/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub

jwt:
  secret: ${JWT_SECRET}
  access-exp: 3600000
  refresh-exp: 604800000

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: hotsix-upload-bucket

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

app:
  oauth2:
    redirect-uri: ${PROD_OAUTH2_REDIRECT_URI}
    cookie:
      access-token:
        name: accessToken
        max-age: 3600
      secure: true
      path: /

openai:
  api-key: ${OPENAI_API_KEY}