spring:
  application:
    name: hotsix

  datasource:
    url: jdbc:mysql://localhost:3306/hotsix_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

jwt:
  secret: ${JWT_SECRET}
  access-exp: 3600000
  refresh-exp: 604800000

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_CREDENTIALS_ACCESSKEY}
      secret-key: ${CLOUD_AWS_CREDENTIALS_SECRETKEY}
    region:
      static: ${CLOUD_AWS_REGION_STATIC}
    s3:
      bucket: hotsix-upload-bucket