spring:
  application:
    name: hotsix

  datasource:
    url: jdbc:mysql://localhost:3306/hotsix_db
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD:}

jwt:
  secret: ${JWT_SECRET}
  access-exp: 3600000
  refresh-exp: 604800000

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
  default-produces-media-type: application/json
  default-consumes-media-type: application/json