spring:
  datasource:
    url: jdbc:mysql://hotsix-db.cbwe20uqwfqp.ap-northeast-2.rds.amazonaws.com:3306/hotsix_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
      timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  access-exp: 3600000
  refresh-exp: 604800000

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: hotsix-upload-bucket

springdoc:
  swagger-ui:
    display-request-duration: true
    doc-expansion: none
  default-produces-media-type: application/json
  default-consumes-media-type: application/json